version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: flux_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: flux_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/flux_db
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - mongo

volumes:
  mongo_data:
